web/weishuku/book/urls.py
from django.conf.urls import patterns, url
from book import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^booklist/$', views.book_list, name='booklist'),
    url(r'^library/$', views.library, name='library'),
    url(r'^addbook/$', views.add_book, name='addbook'),
    url(r'^(?P<id>\d+)/$', views.info_book, name='info_book'),
    url(r'^borrow/$', views.borrow_book, name='borrow_book'),
    url(r'^approve_borrow/(?P<bookid>\d+)/$', views.approve_borrow, name='approve_borrow'),
    url(r'^refuse_borrow/(?P<bookid>\d+)/$', views.refuse_borrow, name='refuse_borrow'),
    url(r'^return/(?P<id>\d+)/$', views.return_book, name='return_book'),
)

web/weishuku/tag/urls.py
from django.conf.urls import patterns, url

from tag import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^taglist/$', views.tag_list, name='taglist'),
)

web/weishuku/weishuku/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('default.urls', namespace='default')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^tag/', include('tag.urls', namespace='tag')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^activity/', include('activity.urls', namespace='activity')),
    url(r'^admin/', include(admin.site.urls)),
)

web/weishuku/book/models.py
from django.db import models

class Book(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=128L)
    publisher = models.CharField(max_length=128L, blank=True)
    isbn = models.CharField(max_length=13L)
    url = models.CharField(max_length=128L, blank=True)
    ispersonal = models.IntegerField(db_column='isPersonal') # Field name made lowercase.
    ownerid = models.IntegerField()
    summary = models.CharField(max_length=1024L, blank=True)
    price = models.FloatField(null=True, blank=True)
    numraters = models.CharField(max_length=45L, db_column='numRaters', blank=True) # Field name made lowercase.
    averagerate = models.IntegerField(null=True, db_column='averageRate', blank=True) # Field name made lowercase.
    created_date = models.DateTimeField(null=True, blank=True)
    updated_date = models.DateTimeField(null=True, blank=True)
    borrowdate = models.DateTimeField(null=True, blank=True)
    author = models.CharField(max_length=128L, blank=True)
    pubdate = models.CharField(max_length=45L, blank=True)
    ispublic = models.IntegerField(null=True, db_column='isPublic', blank=True) # Field name made lowercase.
    imgurl = models.CharField(max_length=128L, db_column='ImgURL', blank=True) # Field name made lowercase.
    class Meta:
        db_table = 'Book'

    def __unicode__(self):
        return self.title


class Borrowrel(models.Model):
    id = models.AutoField(primary_key=True, db_column='Id') # Field name made lowercase.
    bookid = models.IntegerField(db_column='BookID') # Field name made lowercase.
    owner = models.IntegerField(db_column='Owner') # Field name made lowercase.
    borrower = models.IntegerField(db_column='Borrower') # Field name made lowercase.
    status = models.IntegerField(db_column='Status') # Field name made lowercase.
    createdate = models.DateTimeField(db_column='CreateDate') # Field name made lowercase.
    deldate = models.DateTimeField(db_column='DelDate') # Field name made lowercase.
    messageid = models.IntegerField(db_column='MessageID') # Field name made lowercase.
    class Meta:
        db_table = 'BorrowRel'

web/weishuku/book/forms.py
# -*- coding: utf-8 -*-
from django import forms

class BookForm(forms.Form):
    title = forms.CharField(max_length=100)
    publisher = forms.CharField(max_length=100)
    isbn = forms.BooleanField(required=False)
    url = forms.CharField(max_length=100)
    summary = forms.CharField(max_length=100)
    price = forms.CharField(max_length=100)
    numraters = forms.CharField(max_length=100)
    averagerate = forms.CharField(max_length=100)
    #created_date = forms.CharField(max_length=100)
    #updated_date = forms.CharField(max_length=100)
    #borrowdate = forms.CharField(max_length=100)
    author = forms.CharField(max_length=100)
    pubdate = forms.CharField(max_length=100)
    ispublic = forms.CharField(max_length=100)
    ispersonal = forms.CharField(max_length=100)

web/weishuku/book/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page
from django import forms
from django.conf import settings

import json
import datetime

from book.models import Book, Borrowrel
from book.forms import BookForm
from tag.models import Tag, Booktag
from message.models import Message
from url_tool import parse_book_by_url
from url_tool import parse_book_by_id

def index(request):
    return HttpResponse(json.dumps('hello world!'), content_type="application/json")

@cache_page(60 * 60 * 24)
def book_list(request):
    is_login = request.user.is_authenticated()
    q = Book.objects.all()
    book_list = [(item.title,item.isbn) for item in q]
    return HttpResponse(json.dumps(book_list), content_type="application/json")

@login_required
def library(request):
    context = dict()
    q = Book.objects.filter(ownerid=request.user.id)
    book_list = [item for item in q]

    borrow_list = list()
    for rel in Borrowrel.objects.filter(borrower=request.user.id):
        book = Book.objects.filter(id=rel.bookid)[0]
        book.status = rel.status
        borrow_list.append(book)

    return_list = list()
    for rel in Borrowrel.objects.filter(owner=request.user.id):
        book = Book.objects.filter(id=rel.bookid)[0]
        book.status = rel.status
        return_list.append(book)

    context['book_list'] = book_list
    context['is_login'] = request.user.is_authenticated()
    context['username'] = request.user.username
    context['msg_num'] = Message.objects.filter(targetid=request.user.id, status=0).count()
    context['book_num'] = len(book_list)
    context['borrow_num'] = len(borrow_list)
    context['return_num'] = len(return_list)
    context['return_list'] = return_list
    context['borrow_list'] = borrow_list
    return render(request, 'book/library.html', context)

@login_required
def add_book(request):
    context = dict()
    if request.method == 'POST':
        if 'url' in request.POST:
            url = request.POST['url']    
            context = parse_book_by_url(url)
            return render(request, 'book/add.html', context)
        if 'bookid' in request.POST:
            bookid = request.POST['bookid']
            context = parse_book_by_id(bookid)
            book = Book()
            book.title = context['title']
            book.publisher = context['publisher']
            book.isbn = context['isbn10'] if 'isbn10' in context else context['isbn13']
            book.url = context['url']
            book.ispersonal = int(True)
            book.ownerid = request.user.id
            book.summary = context['summary']
            book.price = context['price']
            book.numraters = 0
            book.averageRate = 3
            book.created_date = datetime.datetime.now()
            book.updated_date = datetime.datetime.now()
            book.author = context['author'][0]
            book.pubdate = context['pubdate']
            book.ispublic = int(True)
            book.imgurl = context['images']
            book.save()

            #save tags of book
            for val in context['tags']:
                tag = Tag()
                tag.value = val
                tag.createdate = datetime.datetime.now()
                tag.save()
                rel = Booktag()
                rel.tagid = tag.id
                rel.bookid = book.id
                rel.save()
            return redirect('/book/library', context)
    else:    
        form = BookForm()
        context['form'] = form
        return render(request, 'book/add.html', context)

def info_book(request, id):
    context = dict()
    context['is_login'] = request.user.is_authenticated()
    if request.user.is_authenticated():
        context['username'] = request.user.username
    book = Book.objects.filter(id=id)[0]
    context['book'] = book
    context['userid'] = request.user.id
    context['is_own'] = (book.ownerid == request.user.id)

    context['tags'] = []
    for tagid in [rel.tagid for rel in Booktag.objects.filter(bookid=id)]:
        context['tags'].append(Tag.objects.filter(id=tagid)[0].value)
    return render(request, 'book/detail.html', context)

@login_required
def del_book(request):
    pass
    
@login_required
def update_book(request):
    pass

@login_required
def borrow_book(request):
    if request.method == 'POST' and 'bookid' in request.POST:
        borrower = request.user.id
        book = Book.objects.filter(id=request.POST['bookid'])[0]
        ownerid = book.ownerid

        msg = Message()
        msg.originid = borrower
        msg.targetid = ownerid
        msg.status = 0
        msg.createdate = datetime.datetime.now()
        msg.content = request.POST['message'] 
        msg.handler = '/book/library/'
        msg.save()

        rel = Borrowrel()
        rel.bookid = book.id
        rel.owner = ownerid
        rel.borrower = borrower
        rel.createdate = datetime.datetime.now()
        rel.status = 0
        rel.messageid = msg.id
        rel.save()
        return redirect('/book/library/')

@login_required
def approve_borrow(request, bookid):
    rel = Borrowrel.objects.filter(bookid=bookid)[0]
    rel.status = 2
    rel.save()
    return redirect('/book/library/')

@login_required
def refuse_borrow(request, bookid):
    rel = Borrowrel.objects.filter(bookid=bookid)[0]
    rel.status = 1
    rel.save()
    return redirect('/book/library/')


@login_required
def return_book(request, id):
    context = dict()
    context['is_login'] = request.user.is_authenticated()
    if request.user.is_authenticated():
        context['username'] = request.user.username
    q = Borrowrel.objects.filter(bookid=id, borrower=request.user.id)    
    q[0].delete()
    return redirect('/book/library/')

web/weishuku/book/templates/book/add.html
{% extends 'default/base.html' %}
{% load staticfiles %}
{% block content %}
        <form action="/book/addbook/" method="post" class="form-signin"> {% csrf_token %}
          <input id="url" name="url" class="span2" type="text" maxlength="200" style="width:550px;height:50px;"  placeholder="输入书籍的豆瓣链接">
          <a class="btn btn-lg btn-primary" style="line-height: 1.5;"  role="button" onclick="$(this).closest('form').submit()">解析</a>
        </form>
{% if hasbook %}
        <div class="col-md-12">
            <h2>{{ title }} </h2>
        </div>
        <div class="col-md-2">
            <img src="{{ images }}" class="img-polaroid book_img"> </img>
        </div>
        <div class="col-md-3">
            {% for item in author %}
                <div> 作者：{{ item }}   </div>
            {% endfor %}
            <div> 出版社：{{ publisher}}   </div>
            <div> 出版日期：{{ pubdate }}   </div>
            <div> 页数：{{ pages }}  </div>
            <div> 价格：{{ price }}   </div>
            <div> ISBN：{{ isbn10 }}   </div>
            <div> 豆瓣URL：{{ url }}   </div>
        </div>
        <div class="col-md-3">
            <div id="inner_rating">
                内部评分：
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
            </div> 
            <div id="douban_rating">
                豆瓣评分：
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
            </div>  
            <div id="jingdong_rating">
                京东评分：
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
            </div>  
        </div>
        <div class="col-md-12"> 
            <br/>
            <form action="/book/addbook/" method="post" class="form-signin"> {% csrf_token %}
                <input type="hidden" id="bookid" name="bookid" value="{{bookid}}">
                <button type="submit" class="btn btn-info btn-sm">收入书库</button>
            </form>
        </div>

        <div class="col-md-8">
            <br>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
              <li class="active"><a href="#summary" data-toggle="tab">导言</a></li>
              <li><a href="#author" data-toggle="tab">作者简介</a></li>
              <li><a href="#catalog" data-toggle="tab">目录</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
              <div class="tab-pane fade in active" id="summary">{{summary}}</div>
              <div class="tab-pane fade" id="author">{{author_intro}}</div>
              <div class="tab-pane fade" id="catalog">{{catalog}}</div>
            </div>
        </div>
        <div class="col-md-8">
            <h3> 标签</h3>
            {% for item in tags %}
            <button type="button" class="btn btn-default btn-sm">{{ item }}</button>
            {% endfor %}
        </div>
{% endif %}
{% endblock %}

web/weishuku/book/templates/book/detail.html
{% extends 'default/base.html' %}
{% load staticfiles %}
{% block content %}
        <div class="col-md-12">
            <h2>{{ book.title }} </h2>
        </div>
        <div class="col-md-2">
            <img src="{{ book.imgurl }}" class="img-polaroid book_img"> </img>
        </div>
        <div class="col-md-3">
            <div> 作者：{{ book.author }}   </div>
            <div> 出版社：{{ book.publisher}}   </div>
            <div> 出版日期：{{ book.pubdate }}   </div>
            <div> 页数：{{ book.pages }}  </div>
            <div> 价格：{{ book.price }}   </div>
            <div> ISBN：{{ book.isbn }}   </div>
            <div> 豆瓣URL：{{ book.url }}   </div>
        </div>
        <div class="col-md-3">
            <div id="inner_rating">
                内部评分：
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
            </div> 
            <div id="douban_rating">
                豆瓣评分：
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
            </div>  
            <div id="jingdong_rating">
                京东评分：
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star red_star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
            </div>  
        </div>
        <div class="col-md-12"> 
            <br/>
            <form action="/book/borrow/" method="post" class="form-signin"> {% csrf_token %}
                <input type="hidden" id="bookid" name="bookid" value="{{book.id}}">
                {% if is_own %}
                <button type="button" class="btn btn-info btn-sm">我有本同样的！</button>
                {% else %}
                <input id="message" name="message" class="hidden" type="text" maxlength="100" style="width:550px;" placeholder="说点好听的呗。。。" />
                <button id='borrowBtn' type="button" class="btn btn-info btn-sm">我要借》</button>
                <button id='submitBtn' type="submit" class="btn btn-info btn-sm hidden">提交申请</button>
                {% endif %}
            </form>
        </div>

        <div class="col-md-8">
            <br>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
              <li class="active"><a href="#summary" data-toggle="tab">导言</a></li>
              <li><a href="#author" data-toggle="tab">作者简介</a></li>
              <li><a href="#catalog" data-toggle="tab">目录</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
              <div class="tab-pane fade in active" id="summary">{{book.summary}}</div>
              <div class="tab-pane fade" id="author">{{book.author_intro}}</div>
              <div class="tab-pane fade" id="catalog">{{book.catalog}}</div>
            </div>
        </div>
        <div class="col-md-8">
            <h3> 标签</h3>
            {% for item in tags %}
            <button type="button" class="btn btn-default btn-sm">{{ item }}</button>
            {% endfor %}
        </div>

    <script src="{{STATIC_URL}}js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#borrowBtn").click(function(){
                $("#message").attr("class", "show form-control");
                $("#borrowBtn").attr("class", "hidden");
                $("#submitBtn").attr("class", "btn btn-info btn-sm show");
            }); 
        });
    </script>
{% endblock %}

web/weishuku/book/templates/book/library.html
{% extends 'default/base.html' %}
{% load staticfiles %}
{% block content %}
        {% if book_num == 0 %}
          你的书库中还没有书，赶快去添加一些吧！
          <a href="{% url 'book:addbook' %}" class="btn btn-lg btn-primary" style="line-height: 1.5;"  role="button">添加书籍</a>
        {% else %}
        <div class="col-md-8">
          <div class="col-md-7"> <font size=5> <b>我的书库 </b> </font>  </div>
          <div class="col-md-1">
            <a href="{% url 'book:addbook' %}" class="btn btn-sm btn-info"  role="button">添加更多书籍》
            </a>
          </div>

          <div class="col-md-12"> <hr/></div>
          
          {% for book in book_list %}
            <div class="col-md-3 libray_book">
              <a href="/book/{{ book.id }}">
                <img src="{{book.imgurl}}" class="img-polaroid book_img"> </img>
                <h4>{{ book.title }} </h4>
              </a>
            </div>
          {% endfor %}
        </div>
        {% endif %}

        {% if borrow_num > 0 %}
        <div class="col-md-8">
          <div class="col-md-7"> <font size=5> <b>我借到的书 </b> </font>  </div>

          <div class="col-md-12"> <hr/></div>
          
          {% for book in borrow_list %}
            <div class="col-md-3 libray_book">
              <a href="/book/{{ book.id }}">
                <img src="{{book.imgurl}}" class="img-polaroid book_img"> </img>
                <h4>{{ book.title }} </h4>
              </a>
            <div class="col-md-1">
              {% if book.status == 0 %}
                <a href="/book/return/{{book.id}}" class="btn btn-sm btn-info"  role="button">等待消息</a>
              {% elif book.status == 1 %}
                <a href="/book/return/{{book.id}}" class="btn btn-sm btn-info"  role="button">哎，不借！</a>
              {% else %}
                <a href="/book/return/{{book.id}}" class="btn btn-sm btn-info"  role="button">去还书》</a>
              {% endif %}
          </div>
            </div>
          {% endfor %}
        </div>
        {% endif %}

        {% if return_num > 0 %}
        <div class="col-md-8">
          <div class="col-md-7"> <font size=5> <b>我借出的书 </b> </font>  </div>
          <div class="col-md-1">
            <a href="{% url 'book:addbook' %}" class="btn btn-sm btn-info"  role="button">去催书》
            </a>
          </div>

          <div class="col-md-12"> <hr/></div>
          
          {% for book in return_list %}
            <div class="col-md-3 libray_book">
              <a href="/book/{{ book.id }}">
                <img src="{{book.imgurl}}" class="img-polaroid book_img"> </img>
                <h4>{{ book.title }} </h4>
              </a>
              {% if book.status == 0 %}
              <a href="/book/approve_borrow/{{book.id}}" class="btn btn-sm btn-info">同意</a>
              <a href="/book/refuse_borrow/{{book.id}}" class="btn btn-sm btn-info">不同意</a>
              {% elif book.status == 1 %}
                已拒绝借出
              {% else %}
                已同意借出
              {% endif %}
            </div>
          {% endfor %}
        </div>
        {% endif %}

{% endblock %}