web/weishuku/book/urls.py
from django.conf.urls import patterns, url
from book import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^booklist/$', views.book_list, name='booklist'),
    url(r'^library/$', views.library, name='library'),
    url(r'^addbook/$', views.add_book, name='addbook'),
    url(r'^(?P<id>\d+)/$', views.info_book, name='info_book'),
    url(r'^borrow/$', views.borrow_book, name='borrow_book'),
    url(r'^approve_borrow/(?P<bookid>\d+)/$', views.approve_borrow, name='approve_borrow'),
    url(r'^refuse_borrow/(?P<bookid>\d+)/$', views.refuse_borrow, name='refuse_borrow'),
    url(r'^return/(?P<id>\d+)/$', views.return_book, name='return_book'),
)

web/weishuku/default/urls.py
from django.conf.urls import patterns, url

from default import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

web/weishuku/member/urls.py
from django.conf.urls import patterns, url

from member import views

urlpatterns = patterns('',
    url(r'^login/$', views.my_login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.my_logout, name='logout'),
)

web/weishuku/tag/urls.py
from django.conf.urls import patterns, url

from tag import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^taglist/$', views.tag_list, name='taglist'),
)

web/weishuku/weishuku/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('default.urls', namespace='default')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^tag/', include('tag.urls', namespace='tag')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^activity/', include('activity.urls', namespace='activity')),
    url(r'^admin/', include(admin.site.urls)),
)

web/weishuku/default/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render
import json
import urllib2
from book.models import Book
from tag.models import Tag
from message.models import Message

def index(request):
    context = dict()
    #tag_data = json.load(urllib2.urlopen('http://192.168.8.103:27080/weishuku/booktag/_find'))
    #tag_list = list()
    #for item in tag_data['results']:
    #    tag_list.append(item['name'])
    context['tag_list'] = [tag.value for tag in Tag.objects.all()]
    is_login = request.user.is_authenticated()
    context['is_login'] = is_login
    if is_login:
        context['username'] = request.user.username
        context['msg_num'] = Message.objects.filter(targetid=request.user.id, status=0).count()
    context['book_list'] = [book for book in Book.objects.all()]
    return render(request, 'default/home.html', context)

web/weishuku/default/templates/default/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/extension.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'default:index' %}">微书库</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle active" data-toggle="dropdown">我的书库<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'book:library' %}">拥有的书</a></li>
                <li><a href="#">借到的书</a></li>
                <li><a href="#">关注的书</a></li>
                <li class="divider"></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" >小组</a>
            </li>

            <li>
              <a href="{% url 'activity:index' %}">活动</b></a>
            </li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if is_login %}
            <li class="active"><a href="#">{{ username }}</a></li>
            <li><a href="{% url 'message:index' %}"><span class="glyphicon glyphicon-bell red_star"></span> {{msg_num}}</a></li>
            <li><a href="{% url 'member:logout' %}">注销</a></li>
            {% else %}
            <li class="active"><a href="{% url 'member:login' %}">登陆</a></li>
            <li><a href="{% url 'member:register' %}">注册</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>

        <div>
          {% block content %} {% endblock %}
        </div>

        <div id="footer" class="col-md-12">
            <hr>
            © 2005－2013 nianyike.com, all rights reserved
        </div>
    </div> <!-- /container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{STATIC_URL}}js/jquery-1.10.2.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
  </body>
</html>

web/weishuku/default/templates/default/home.html
{% extends 'default/base.html' %}
{% load staticfiles %}
{% block content %}
      <div class="jumbotron">
        <b><font size="16">心在远方，书在身边</font></b>
        <form>
          <input class="span2" type="text" maxlength="20" style="width:550px;" 
                placeholder="感兴趣的作者，书和小组">
          <a class="btn btn-lg btn-primary" style="line-height: 1.5;"  role="button">搜索</a>
        </form>
          
        </p>
      </div>

        <div class="col-md-8">
            <h2>达人推荐</h2>
            {% for book in book_list %}
            <div class="col-md-3 libray_book">
              <a href="/book/{{ book.id }}">
                <img src="{{book.imgurl}}" class="img-polaroid book_img"> </img>
                <h4>{{ book.title }} </h4>
              </a>
            </div>
           {% endfor %}
        </div>

        <div class="col-md-4">
          <h2>热门标签</h2>
          {% for item in tag_list %}
            {{ item }} </br>
          {% endfor %}
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
      </div>

{% endblock %}