web/weishuku/member/urls.py
from django.conf.urls import patterns, url

from member import views

urlpatterns = patterns('',
    url(r'^login/$', views.my_login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.my_logout, name='logout'),
)

web/weishuku/tag/urls.py
from django.conf.urls import patterns, url

from tag import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^taglist/$', views.tag_list, name='taglist'),
)

web/weishuku/weishuku/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('default.urls', namespace='default')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^tag/', include('tag.urls', namespace='tag')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^activity/', include('activity.urls', namespace='activity')),
    url(r'^admin/', include(admin.site.urls)),
)

web/weishuku/member/models.py
from django.db import models

# Create your models here.

web/weishuku/member/forms.py
# -*- coding: utf-8 -*-
from django import forms

class LoginForm(forms.Form):
    account = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)
    remember = forms.BooleanField(required=False)
    next =  forms.CharField(max_length=100)

class RegisterForm(forms.Form):
    account = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)
    repeat_password = forms.CharField(max_length=100)
    remember = forms.BooleanField(required=False)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password1 = cleaned_data.get("password")
        password2 = cleaned_data.get("repeat_password")

        if password1 == None or password2 == None or password1 != password2:
            #self.add_error('password', '密码不一致')
            raise forms.ValidationError('密码不一致')
        return cleaned_data

web/weishuku/member/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required

from member.forms import LoginForm, RegisterForm



def my_login(request):
    context = dict()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            account = form.cleaned_data['account']
            password = form.cleaned_data['password']
            remember = form.cleaned_data['remember']
            next = form.cleaned_data['next']
            user = authenticate(username=account, password=password)
            if user is not None:
                login(request, user)
                #print 'user of session:%s' % (request.user.is_authenticated())
                #print 'user of name:%s ' % request.user.username
                #return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                return redirect(next, context)
            else:
                context['form'] = LoginForm()
                context['next'] = next
                return render(request, 'member/login.html', context)
    else:
        next = '/'
        if 'next' in request.GET:
            next = request.GET['next']
        context['form'] = LoginForm()
        context['next'] = next
    return render(request, 'member/login.html', context)

@login_required
def my_logout(request):
    logout(request)
    return redirect('/')

def register(request):
    context = dict()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            account = form.cleaned_data['account']
            password = form.cleaned_data['password']
            remember = form.cleaned_data['remember']
            user = User.objects.create_user(username=account, password=password)
            user = authenticate(username=account, password=password)
            if user is not None:
                login(request, user)
            return redirect('/', context)
        else:
            context['form'] = form
            return render(request, 'member/register.html', context)
    else:
        context['form'] = RegisterForm()
        return render(request, 'member/register.html', context)

web/weishuku/member/templates/member/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/signin.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <form action="/member/login/" method="post" class="form-signin"> {% csrf_token %}
        {{ form.account.errors }}
        {{ form.password.errors }}
        {{ form.remember.errors }}
        <h2 class="form-signin-heading">亲，我们又见面了！</h2>
        <input id="id_account" name="account" type="text" class="form-control" placeholder="邮件地址" required autofocus>
        <input id="id_password" name="password" type="password" class="form-control" placeholder="密码" required>
        <label class="checkbox">
          <input id="id_remember" type="checkbox" value="remember-me"> 记住我
        </label>
        <input type="hidden" id="id_next" name="next" value="{{next}}">
        <button class="btn btn-lg btn-primary btn-block" type="submit">登陆</button>
      </form>
    </div><!-- /container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{STATIC_URL}}js/jquery-1.10.2.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
  </body>
</html>

web/weishuku/member/templates/member/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/signin.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <form action="/member/register/" method="post" class="form-signin"> {% csrf_token %}
        <h2 class="form-signin-heading">注册好处多多！</h2>
        <input id="id_account" name="account" type="text" class="form-control" placeholder="邮件地址" required autofocus>
        <input id="id_password" name="password" type="password" class="form-control" placeholder="密码" required>
        <input id="id_repeat_password" name="repeat_password" type="password" class="form-control" placeholder="重复密码" required>
        <font color="red" size=5> {{ form.non_field_errors }} </font>
        <label class="checkbox">
          <input id="id_remember" type="checkbox" value="remember-me"> 记住我
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
      </form>
    </div><!-- /container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{STATIC_URL}}js/jquery-1.10.2.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
  </body>
</html>